### ISSUE TITLE
Бесконечная загрузка в блоке с информацией о тесте при первом открытии страницы

### ISSUE THREAD

**Issue by zomlik** [AlbShar/quizFrontend#50]
1. Открыть страницу в режиме инкогнито https://albshar.github.io/quizFrontend/ 

![2023-11-02_12-29-39](https://github.com/AlbShar/quizFrontend/assets/69787064/132d292c-3933-4498-815f-20b5cdb27d84)

Win10, Chrome 119.0.6045.105

**Comment by AlbShar** [comment]
Баг исправлен.
